/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false --strict-vars false` (hash: 3689c5532c5be62fd4b088927d78e84d)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "RealtimeDurableObject";
	}
	interface Env {
		REALTIME_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").RealtimeDurableObject>;
	}
}
interface Env extends Cloudflare.Env {}
