/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false --strict-vars false` (hash: 031ec7eebf47f6f2f2202478269694b1)
declare namespace Cloudflare {
	interface Env {
		DEV: string;
		REALTIME_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").RealtimeDurableObject>;
	}
}
interface Env extends Cloudflare.Env {}
